### ISSUE TITLE
sqlalchemy.orm.DetachedInstanceError

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite-pg-redis-docker#11]
```python exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlite/app.py", line 149, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlite/asgi.py", line 70, in __call__
    await route.handle(scope=scope, receive=receive, send=send)
  File "/usr/local/lib/python3.10/site-packages/starlite/routes.py", line 149, in handle
    response = await route_handler.to_response(
  File "/usr/local/lib/python3.10/site-packages/starlite/handlers/http.py", line 312, in to_response
    data = plugin.to_dict(data)
  File "/usr/local/lib/python3.10/site-packages/starlite/plugins/sql_alchemy.py", line 325, in to_dict
    kwargs[field] = getattr(model_instance, field)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 481, in __get__
    return self.impl.get(state, dict_)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 941, in get
    value = self._fire_loader_callables(state, key, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 977, in _fire_loader_callables
    return self.callable_(state, passive)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 862, in _load_for_state
    raise orm_exc.DetachedInstanceError(
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <User at 0x7fd6666374f0> is not bound to a Session; lazy load operation of attribute 'items' cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)
```
For ref. in PR.

**Comment by peterschutt** [comment]
This hasn't been so much fixed as avoided. I need to work out the best way to configure the eager loading. On the declarative model itself is the most straightforward, but maybe open to forgetting about.. maybe could  define them with the dependency system so that the default way to load a relationship could be defined at the application level and get more specific with overrides on the controller or handler level.

Will leave this open until I settle on something. Mostly I try to avoid loading 1 to n relationships and prefer nesting routes.
