### ISSUE TITLE
Bug: cannot enable openapi docs

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite-pg-redis-docker#67]
If openapi docs are enabled, either through using the app's config object, or the default config object from starlite, the app crashes on startup. Only way to get it to run is to set `openapi_config=None`.

```
app_1    | Error while loading the application:
app_1    | 
app_1    | Traceback (most recent call last):
app_1    |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 208, in run
app_1    |     self.load()
app_1    |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
app_1    |     return self.load_wsgiapp()
app_1    |   File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
app_1    |     return util.import_app(self.app_uri)
app_1    |   File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
app_1    |     mod = importlib.import_module(module)
app_1    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
app_1    |     return _bootstrap._gcd_import(name[level:], package, level)
app_1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
app_1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
app_1    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
app_1    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
app_1    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
app_1    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
app_1    |   File "/app/app/main.py", line 9, in <module>
app_1    |     app = Starlite(
app_1    |   File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
app_1    |   File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
app_1    |   File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
app_1    |   File "/usr/local/lib/python3.10/site-packages/starlite/app.py", line 283, in __init__
app_1    |     self.openapi_schema = self.openapi_config.create_openapi_schema_model(self)
app_1    |   File "/usr/local/lib/python3.10/site-packages/starlite/config/openapi.py", line 180, in create_openapi_schema_model
app_1    |     return construct_open_api_with_schema_class(schema)
app_1    |   File "/usr/local/lib/python3.10/site-packages/pydantic_openapi_schema/utils/utils.py", line 62, in construct_open_api_with_schema_class
app_1    |     schema_definitions = schema(schema_classes, by_alias=by_alias, ref_prefix=REF_PREFIX)["definitions"]
app_1    |   File "pydantic/schema.py", line 145, in pydantic.schema.schema
app_1    |   File "pydantic/schema.py", line 580, in pydantic.schema.model_process_schema
app_1    |   File "pydantic/schema.py", line 621, in pydantic.schema.model_type_schema
app_1    |   File "pydantic/schema.py", line 254, in pydantic.schema.field_schema
app_1    |   File "pydantic/schema.py", line 526, in pydantic.schema.field_type_schema
app_1    |   File "pydantic/schema.py", line 921, in pydantic.schema.field_singleton_schema
app_1    |   File "/usr/local/lib/python3.10/abc.py", line 123, in __subclasscheck__
app_1    |     return _abc_subclasscheck(cls, subclass)
app_1    | TypeError: issubclass() arg 1 must be a class
starlite-pg-redis-docker_app_1 exited with code 1
```

**Comment by peterschutt** [comment]
Thanks!
